In [74]:
import pandas as pd

sold = pd.read_csv('idx_files/residential_sold.csv')
listing = pd.read_csv('idx_files/residential_listings.csv')

/var/folders/15/fxy7kh_n2sbbwk9d_48fvvh40000gn/T/ipykernel_2712/1142117879.py:3: DtypeWarning: Columns (0,1,64,78,79,80,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv('idx_files/residential_sold.csv')
/var/folders/15/fxy7kh_n2sbbwk9d_48fvvh40000gn/T/ipykernel_2712/1142117879.py:4: DtypeWarning: Columns (43) have mixed types. Specify dtype option on import or set low_memory=False.
  listing = pd.read_csv('idx_files/residential_listings.csv')

In [75]:
sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
2,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1079166779,davidmartz@compass.com,...,92262,NaN,13504.0,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
4,Southland,Southland,NaN,False,NaN,NaN,False,1890500.0,1075037759,karen.klein@theagencyre.com,...,91356,0.0,17873.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414058,LakeCounty,LakeCounty,NaN,True,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,...,95424,0.0,10019.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
414059,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,NaN,True,False,449000.0,1067010583,brian@cohen-realty.com,...,92322,0.0,12096.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
414060,SanDiego,TriCounties,Vinyl,True,NaN,NaN,False,1579000.0,1063196193,info@homecoin.com,...,93619,0.0,859874.4,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
414061,Mrmls,OrangeCounty,NaN,True,NaN,NaN,False,855000.0,1062106215,jefflachef@gmail.com,...,92629,0.0,2733.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
414062,Southland,PacificWest,"Carpet,Vinyl",False,NaN,NaN,False,375000.0,1052387780,elizabethoryan04@gmail.com,...,90302,345.0,23878.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN

In [76]:
listing

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.00,5300.0,NaN,16 Palisades
2,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaN,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,1.0,False,4.0,Walnut Valley Unified,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaN,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,3.0,False,2.0,Newport Mesa Unified,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567544,2595000.0,1153444674,denny@dennykagasoff.com,NaN,NaN,Denny,Kagasoff,34.129724,-118.394741,12004 Briarvale Lane,...,NaN,False,NaN,NaN,91604,NaN,NaN,24226.0,NaN,12004 Briarvale Lane
567545,7285000.0,1152609167,ann@brizolisjanzen.com,NaN,NaN,K. Ann,Brizolis,32.980315,-117.198367,14480 Bellvista Dr,...,NaN,False,3.0,NaN,92067,NaN,735.00,NaN,NaN,14480 Bellvista Dr
567546,396000.0,1151471220,jason@venture-pacific.net,NaN,NaN,Jason,Lipovsky,33.002752,-116.782659,15755 Davis Cup Lane,...,1.0,NaN,0.0,Ramona Unified,92065,NaN,596.00,831560.4,NaN,15755 Davis Cup Lane
567547,985000.0,1149517845,aisaethan@icloud.com,NaN,NaN,Aisa,Tu,33.645255,-117.358172,33115 Evergreen Sreet,...,2.0,NaN,3.0,Lake Elsinore Unified,92530,NaN,0.00,14810.0,NaN,33115 Evergreen Sreet
567548,450000.0,1147219386,nathaly@shoppingsdhouses.com,NaN,NaN,Nathaly,Vera,32.746368,-116.984283,9860 Dale Avenue D2,...,NaN,NaN,0.0,Other,91977,NaN,510.00,91040.4,NaN,9860 Dale Avenue D2

In [77]:
print(sold.columns.unique())
print(listing.columns.unique())

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='object')
Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='object')

In [78]:
# identify the number of rows and columns
print(sold.shape)
print(listing.shape)

(414063, 84)
(567549, 84)

In [79]:
# identify the data types in the columns
print(sold.dtypes)
print(listing.dtypes)

BuyerAgentAOR                   object
ListAgentAOR                    object
Flooring                        object
ViewYN                          object
WaterfrontYN                    object
                                ...
OriginatingSystemSubName        object
BuyerAgencyCompensationType     object
BuyerAgencyCompensation        float64
latfilled                       object
lonfilled                       object
Length: 84, dtype: object
OriginalListPrice               float64
ListingKey                        int64
ListAgentEmail                   object
CloseDate                        object
ClosePrice                      float64
                                 ...
BuyerOfficeName.1                object
AssociationFee                  float64
LotSizeSquareFeet               float64
MiddleOrJuniorSchoolDistrict    float64
UnparsedAddress.1                object
Length: 84, dtype: object

In [80]:
# missing counts
missing_count = sold.isna().count()
print(missing_count)

BuyerAgentAOR                  414063
ListAgentAOR                   414063
Flooring                       414063
ViewYN                         414063
WaterfrontYN                   414063
                                ...
OriginatingSystemSubName       414063
BuyerAgencyCompensationType    414063
BuyerAgencyCompensation        414063
latfilled                      414063
lonfilled                      414063
Length: 84, dtype: int64

In [81]:
# identify missing values
missing_prop = round((sold.isna().mean()), 2)
print(missing_prop)

BuyerAgentAOR                  0.12
ListAgentAOR                   0.11
Flooring                       0.36
ViewYN                         0.09
WaterfrontYN                   1.00
                               ...
OriginatingSystemSubName       0.87
BuyerAgencyCompensationType    0.89
BuyerAgencyCompensation        0.89
latfilled                      0.85
lonfilled                      0.85
Length: 84, dtype: float64

In [82]:
# identify which columns to drop
cols = missing_prop[missing_prop>0.90].index
cols

Index(['WaterfrontYN', 'BasementYN', 'FireplacesTotal',
       'AboveGradeFinishedArea', 'TaxAnnualAmount', 'BuilderName', 'TaxYear',
       'BuildingAreaTotal', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'BelowGradeFinishedArea', 'BusinessType',
       'CoveredSpaces', 'LotSizeDimensions', 'MiddleOrJuniorSchoolDistrict'],
      dtype='object')

In [83]:
# drop columns with missing values over 90%
sold = sold.drop(columns = cols)
sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,Other,94401,6472.0,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,SanDiego,SanDiego,NaN,False,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,NaN,91950,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
2,SanDiego,SanDiego,NaN,False,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,NaN,91950,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1079166779,davidmartz@compass.com,2024-01-30,858000.0,...,Palm Springs Unified,92262,NaN,13504.0,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
4,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,Los Angeles Unified,91356,0.0,17873.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414058,LakeCounty,LakeCounty,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,2026-04-01,215000.0,...,Konocti Unified,95424,0.0,10019.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
414059,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,False,449000.0,1067010583,brian@cohen-realty.com,2026-04-13,415000.0,...,Rim of the World,92322,0.0,12096.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
414060,SanDiego,TriCounties,Vinyl,True,False,1579000.0,1063196193,info@homecoin.com,2026-04-16,1355000.0,...,Sanger Unified,93619,0.0,859874.4,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
414061,Mrmls,OrangeCounty,NaN,True,False,855000.0,1062106215,jefflachef@gmail.com,2026-04-16,820000.0,...,Capistrano Unified,92629,0.0,2733.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
414062,Southland,PacificWest,"Carpet,Vinyl",False,False,375000.0,1052387780,elizabethoryan04@gmail.com,2026-04-24,380000.0,...,Inglewood Unified,90302,345.0,23878.0,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN